app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from bookstore import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="main_page"),
    path('books/', include(('bookstore.urls', 'bookstore'), namespace='books'))
]

app/bookstore/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.create_book, name="create_book"),
    path('<int:pk>/', views.edit_book, name="edit_book"),
]

app/bookstore/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils.timezone import now
import logging

from .validators import validate_isbn


ISBN_LENGTH = 13
MAX_PRICE_DIGITS = 6
MAX_PRICE_DECIMAL_PLACES = 2

logger = logging.getLogger(__name__)


class Book(models.Model):
    title = models.TextField(verbose_name=_('title'))
    authors_info = models.TextField(verbose_name=_('authors information'))
    isbn = models.CharField(verbose_name=_('ISBN'), max_length=ISBN_LENGTH,
                            validators=[validate_isbn])
    price = models.DecimalField(verbose_name=_('price'),
                                max_digits=MAX_PRICE_DIGITS,
                                decimal_places=MAX_PRICE_DECIMAL_PLACES)
    publish_date = models.DateField(verbose_name=_('publish date'),
                                    default=now)

    def __str__(self):
        return self.title

    def __repr__(self):
        return f"<Book {self.pk}"

    def delete(self, using=None, keep_parents=False):
        logger.info(f"Deleted book: {self.title}")
        super(Book, self).delete(using=using, keep_parents=keep_parents)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if self.pk is None:
            logger.info(f"Created book: {self.title}")
        else:
            logger.info(f"Updated book: {self.title}")

        super(Book, self).save(force_insert=force_insert,
                               force_update=force_update, using=using,
                               update_fields=update_fields)

app/core/models.py
from django.db import models


class WebRequest(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    host = models.CharField(max_length=1000)
    path = models.CharField(max_length=1000)
    method = models.CharField(max_length=50)
    uri = models.CharField(max_length=2000)
    status_code = models.IntegerField()
    user_agent = models.CharField(max_length=1000, blank=True, null=True)
    remote_addr = models.GenericIPAddressField()

    def __str__(self):
        return f"{self.path} - {self.status_code}"

    def __repr__(self):
        return f"<WebRequest {self.pk}"

app/bookstore/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

        widgets = {
            'publish_date': forms.SelectDateWidget,
        }

app/bookstore/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.forms.models import model_to_dict

from .models import Book
from .forms import BookForm
from core.models import WebRequest


BOOKS_PER_PAGE = 10
WEB_REQUEST_LIMIT = 10
INDEX_TITLE = 'Books list'
CREATE_BOOK_TITLE = 'Create Book'
EDIT_BOOK_TITLE = 'Edit Book'


def index(request):
    page_number = request.GET.get('page', 1)

    books = Book.objects.all()

    paginator = Paginator(books, BOOKS_PER_PAGE)

    books = paginator.get_page(page_number)

    web_requests = WebRequest.objects.all()\
        .order_by('-time')[:WEB_REQUEST_LIMIT]

    return render(request, 'index.html', {
        'title': INDEX_TITLE,
        'books': books,
        'web_requests': web_requests,
    })


def create_book(request):

    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New Book was created")
    else:
        form = BookForm()

    return render(request, 'bookstore/create_book.html', {
        'title': CREATE_BOOK_TITLE,
        'form': form,
    })


def edit_book(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, 'Book was edited')
    else:
        form = BookForm(instance=book)

    return render(request, 'bookstore/edit_book.html', {
        'title': EDIT_BOOK_TITLE,
        'form': form,
    })

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

{% block content %}

{% endblock %}

<footer>
    <p class="text-center">2019-{% now 'Y' %}</p>
</footer>

</body>
</html>

app/templates/bookstore/create_book.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.success %} class="{{ message.success }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="col-12">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Send</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/bookstore/edit_book.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.success %} class="{{ message.success }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="col-12">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Send</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <p><a href="{% url 'books:create_book' %}">Create New Book</a></p>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Authors</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Price</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for book in books %}
                    <tr>
                        <th scope="row">{{ book.pk }}</th>
                        <th>{{ book.title }}</th>
                        <th>{{ book.authors_info }}</th>
                        <th>{{ book.isbn }}</th>
                        <th>{{ book.price }}</th>
                        <th><a href="{% url 'books:edit_book' pk=book.pk %}">Edit Book</a></th>
                        <th><a href="{% url 'admin:bookstore_book_change' object_id=book.pk %}">Admin Edit Book</a></th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link"
                           {% if books.has_previous %}href="{% url 'main_page' %}?page={{ books.previous_page_number }}"{% endif %}>Previous</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link"
                           {% if books.has_next %}href="{% url 'main_page' %}?page={{ books.next_page_number }}"{% endif %}>Next</a>
                    </li>
                </ul>
            </nav>

            <table>
                <thead>
                <tr>
                    <th scope="col">Time</th>
                    <th scope="col">URI</th>
                    <th scope="col">Method</th>
                    <th scope="col">Status Code</th>
                    <th scope="col">User Agent</th>
                    <th scope="col">Remote Address</th>
                </tr>
                </thead>
                <tbody>
                {% for web_request in web_requests %}
                    <tr>
                        <th scope="row">{{ web_request.time|date:"Y-m-d" }}</th>
                        <th>{{ web_request.uri }}</th>
                        <th>{{ web_request.method }}</th>
                        <th>{{ web_request.status_code }}</th>
                        <th>{{ web_request.user_agent }}</th>
                        <th>{{ web_request.remote_addr }}</th>
                        <th></th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}